version: 2

always_pending:
  title_regex: '(WIP|DO NOT MERGE)'
  labels:
    - do-not-merge
    - wip
  explanation: 'Work in progress - do not merge'

group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(LGTM|lgtm|Approved|\+1|:\+1:)'
    reject_regex: '^(Rejected|-1|:-1:)'
  # reset approval on push
  reset_on_push:
    enabled: true
  # reset approval on re-open
  reset_on_reopened:
    enabled: true
  # author approval doesn't count
  author_approval:
    ignored: true

groups:
  required: 1
  teams:
    - Core