dist: trusty
sudo: required

branches:
  only:
    - master

env:
  - VERSION=$TRAVIS_COMMIT

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - make pull build gh-pages 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
    make tag push;
    fi

notifications:
  slack: 
    on_success: always 
    on_failure: always
    rooms:
      - secure: $SLACK_KUBERNIKUS 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  local_dir: gh-pages 
  on:
    branch: master
