{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
{{- if .Values.backup.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port:   "8080"
{{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 2379
    name: etcd
  - port: 8080
    name: backup
  selector:
    app: {{ include "fullname" . }}
