kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name | quote }}
  labels:
    tier: kubernikus
    app: prometheus
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
