# Default values for blackbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: prom/blackbox-exporter
  tag: v0.11.0
  pullPolicy: IfNotPresent
service:
  name: blackbox-exporter
  type: ClusterIP
  externalPort: 9115
  internalPort: 9115
