apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: kubernikus-api
  annotations:
    vice-president: "true"
spec:
  tls:
     - secretName: kubernikus-api
       hosts: [{{ required "domain missing" .Values.domain }}]
  rules:
    - host: {{ required "domain missing" .Values.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: kubernikus-api
            servicePort: {{ .Values.api.port }}
        - path: /prometheus
          backend:
            serviceName: kubernikus-prometheus
            servicePort: 9090
