{{- $values := .Values }}
{{- range $path, $bytes := .Files.Glob "grafana/datasources/*.yaml" }}
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: kubernikus-grafana-datasource-{{ printf "%s" $path | replace "/" "-"  }}
  labels:
    kubernikus-grafana-datasource: "true"

data:
{{ printf "%s" $path | replace "/" "-" | indent 2 }}: |
{{ printf "%s" $bytes | indent 4 }}

{{- end }}
