apiVersion: v1
kind: Secret

metadata:
  name: prometheus-openstack-sso-cert

data:
  sso.crt: {{ default "this must exist but cannot be empty" .Values.authentication.ssoCert | b64enc | quote }}
  sso.key: {{ default "this must exist but cannot be empty" .Values.authentication.ssoKey | b64enc | quote }}
