apiVersion: v1
kind: ConfigMap
metadata:
  name: node-problem-detector-config

data:
{{- range $path, $bytes := .Files.Glob "plugins/*.json" }}
{{ printf "%s" $path | trimPrefix "plugins/" | indent 2 }}: |
{{ printf "%s" $bytes | indent 4 }}
{{ end -}}
