post_failure_to_slack: &post_failure_to_slack
  put: slack-alert
  params:
    channel: '#kubernikus'
    username: 'Concourse'
    icon_emoji: ':airplane:'
    silent: 'true'
    text: |
      :boom: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job #$BUILD_NAME failed>
      To debug run `fly hijack -j $BUILD_PIPELINE_NAME/$BUILD_JOB_NAME -b $BUILD_NAME`

resources:

  - name: kubernikusctl.release
    type: github-release
    source:
      owner: sapcc
      repository: kubernikus
      access_token: ((github-com-access-token))

  - name: kubernikus.builds
    type: gh-status
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      owner:    sapcc
      repo:     kubernikus
      access_token: ((github-com-access-token))
      branch: master
      depth: 1
      ignore_paths: ["charts", "ci"]

  - name: daily
    type: time
    source: {interval: 24h}


resource_types:
  - name: time-version
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/time-version-resource
      tag: v2
  - name: slack-notification
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/slack-notification-resource
      tag: latest
  - name: gh-status
    type: docker-image
    source:
      repository: hub.global.cloud.sap/concourse/ghstatus-resource
      tag: latest

jobs:
####################################################################################
#
# kubernikus
#
####################################################################################


  - name: master 
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          trigger: true

  - name: feature 
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          trigger: true

  - name: e2e
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          passed: [master]
          trigger: true

  - name: conformance 
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          passed: [master]
        - get: daily
          trigger: true

  - name: test 
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.builds
          passed: [feature]
          trigger: true

  - name: admin 
    serial: true
    plan:
      - get: kubernikus.builds
        trigger: true
        passed: [e2e]

  - name: integration 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [test]
        trigger: true

  - name: prod 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [e2e]
      - put: kubernikusctl.release

  - name: emea 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [prod]

  - name: asia
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [prod]

  - name: americas 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [prod]

  - name: global 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [admin]
        trigger: true

  - name: staging 
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [integration]
        trigger: true


  - name: qa
    serial: true
    plan:
      - get: kubernikus.builds
        passed: [integration]
        trigger: true

