{{- if .Values.openstack }}
{{- if (semverCompare ">= 1.20" .Values.version.kubernetes) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master.fullname" . }}-csi
  namespace: {{ .Release.Namespace }}
  labels:
    app: csi
    role: controller
spec:
  replicas: {{ .Values.csi.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: csi
      role: controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
{{- if .Values.csi.podAnnotations }}
      annotations:
{{ toYaml .Values.csi.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: csi
        role: controller
    spec:
      containers:
      - name: cinder-csi-plugin
        image: {{ include "cinderCSIPlugin.image" . }}
        imagePullPolicy: IfNotPresent
        args :
        - /bin/cinder-csi-plugin
        - --nodeid=dummy
        - --endpoint=$(CSI_ENDPOINT)
        - --cloud-config=/etc/kubernetes/cloudprovider/openstack.config
        - --cluster={{ include "master.fullname" . }}
        - --v=3
        env:
        - name: CSI_ENDPOINT
          value: unix://{{ .Values.csi.socketPath }}/csi.sock
{{- if .Values.csi.resources.driver }}
        resources:
{{ toYaml .Values.csi.resources.driver | indent 10 }}
{{- end }}
        ports:
        - name: healthz
          containerPort: 9808
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.csi.socketPath }}
        - name: cloud-provider-config
          mountPath: /etc/kubernetes/cloudprovider
        # Host certificates are mounted to accommodate OpenStack endpoints that might be served with a certificate
        # signed by a CA that is not globally trusted.
        #- mountPath: /usr/share/ca-certificates
        #  name: usr-share-ca-certificates
        #  readOnly: true
        #- mountPath: /etc/ssl
        #  name: etc-ssl
        #  readOnly: true

      - name: csi-provisioner
        image: {{ include "csiProvisioner.image" . }}
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=$(ADDRESS)
        - --kubeconfig=/etc/kubernetes/config/csi-kubeconfig
        - --feature-gates=Topology=true
        - --volume-name-prefix=pv-{{ .Release.Namespace }}
        - --default-fstype=ext4
        - --leader-election={{ .Values.csi.leaderElection }}
        {{- if .Values.csi.leaderElectionNamespace }}
        - --leader-election-namespace={{ .Values.csi.leaderElectionNamespace }}
        {{- end }}
        - --timeout={{ .Values.csi.timeout }}
        - --v=5
        env:
        - name: ADDRESS
          value: {{ .Values.csi.socketPath }}/csi.sock
{{- if .Values.csi.resources.provisioner }}
        resources:
{{ toYaml .Values.csi.resources.provisioner | indent 10 }}
{{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.csi.socketPath }}
        - mountPath: /etc/kubernetes/config
          name: config
          readOnly: true
        - mountPath: /etc/kubernetes/certs/
          name: certs
          readOnly: true

      - name: csi-attacher
        image: {{ include "csiAttacher.image" . }}
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=$(ADDRESS)
        - --kubeconfig=/etc/kubernetes/config/csi-kubeconfig
        - --leader-election={{ .Values.csi.leaderElection }}
        {{- if .Values.csi.leaderElectionNamespace }}
        - --leader-election-namespace={{ .Values.csi.leaderElectionNamespace }}
        {{- end }}
        - --timeout={{ .Values.csi.timeout }}
        - --v=5
        env:
        - name: ADDRESS
          value: {{ .Values.csi.socketPath }}/csi.sock
{{- if .Values.csi.resources.attacher }}
        resources:
{{ toYaml .Values.csi.resources.attacher | indent 10 }}
{{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.csi.socketPath }}
        - mountPath: /etc/kubernetes/config
          name: config
          readOnly: true
        - mountPath: /etc/kubernetes/certs/
          name: certs
          readOnly: true

      - name: csi-snapshotter
        image: {{ include "csiSnapshotter.image" . }}
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=$(CSI_ENDPOINT)
        - --kubeconfig=/etc/kubernetes/config/csi-kubeconfig
        - --leader-election={{ .Values.csi.leaderElection }}
        {{- if .Values.csi.leaderElectionNamespace }}
        - --leader-election-namespace={{ .Values.csi.leaderElectionNamespace }}
        {{- end }}
        - --timeout={{ .Values.csi.timeout }}
        - --snapshot-name-prefix={{ .Release.Namespace }}
        env:
        - name: CSI_ENDPOINT
          value: {{ .Values.csi.socketPath }}/csi.sock
{{- if .Values.csi.resources.snapshotter }}
        resources:
{{ toYaml .Values.csi.resources.snapshotter | indent 10 }}
{{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.csi.socketPath }}
        - mountPath: /etc/kubernetes/config
          name: config
          readOnly: true
        - mountPath: /etc/kubernetes/certs/
          name: certs
          readOnly: true

      - name: csi-resizer
        image: {{ include "csiResizer.image" . }}
        imagePullPolicy: IfNotPresent
        args:
        - --csi-address=$(ADDRESS)
        - --kubeconfig=/etc/kubernetes/config/csi-kubeconfig
        - --leader-election={{ .Values.csi.leaderElection }}
        {{- if .Values.csi.leaderElectionNamespace }}
        - --leader-election-namespace={{ .Values.csi.leaderElectionNamespace }}
        {{- end }}
        - --csiTimeout={{ .Values.csi.timeout }}
        - --v=5
        env:
        - name: ADDRESS
          value: {{ .Values.csi.socketPath }}/csi.sock
{{- if .Values.csi.resources.resizer }}
        resources:
{{ toYaml .Values.csi.resources.resizer | indent 10 }}
{{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.csi.socketPath }}
        - mountPath: /etc/kubernetes/config
          name: config
          readOnly: true
        - mountPath: /etc/kubernetes/certs/
          name: certs
          readOnly: true

      - name: csi-liveness-probe
        image: {{ include "csiLivenessProbe.image" . }}
        args:
        - --csi-address=/csi/csi.sock
{{- if .Values.csi.resources.livenessProbe }}
        resources:
{{ toYaml .Values.csi.resources.livenessProbe | indent 10 }}
{{- end }}
        volumeMounts:
        - name: socket-dir
          mountPath: /csi

      volumes:
      - name: socket-dir
        emptyDir: {}
      - name: config
        configMap:
          name: {{ include "master.fullname" . }}
      #- name: usr-share-ca-certificates
      #  hostPath:
      #    path: /usr/share/ca-certificates
      - name: cloud-provider-config
        secret:
          secretName: {{ include "master.fullname" . }}-generated
          items:
          - key: openstack-csi.config
            path: openstack.config
      # Host certificates are mounted to accommodate OpenStack endpoints that might be served with a certificate
      # signed by a CA that is not globally trusted.
      #- name: etc-ssl
      #  hostPath:
      #    path: /etc/ssl
      - name: certs
        secret:
          secretName: {{ .Values.secretName }}
          items:
          - key: tls-ca.pem
            path: tls-ca.pem
          - key: apiserver-clients-csi-controller.pem
            path: csi-client.pem
          - key: apiserver-clients-csi-controller-key.pem
            path: csi-client.key
{{- end }}
{{- end }}
