{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
type: Opaque
data:
  openstack.config: {{ include (print $.Template.BasePath "/_openstack.config.tpl") . | b64enc}}
  token.csv: {{ include (print $.Template.BasePath "/_token.csv.tpl") . | b64enc }}
